x-defaults: &defaults
  image: ghcr.io/chainlabsio/subsquid:main
  restart: always
  environment:
    - DB_NAME=squid
    - DB_PORT=5432
    - DB_HOST=db
    - DB_PASS=postgres
  depends_on:
    - db
  env_file:
    - .env

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      # Uncomment for logging all SQL statements
      # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./db-data:/var/lib/postgresql/data

  api:
    <<: *defaults
    ports:
      # GraphQL endpoint at port 4350
      - "4350:4350"
    command: ["sqd", "serve:prod"]

  arbitrum-processor:
    <<: *defaults
    ports:
      # prometheus metrics exposed at port 3003
      - "3003:3000"
    command: ["sqd", "process:prod:arbitrum"]
    profiles:
      - arbitrum

  avax-processor:
    <<: *defaults
    ports:
      # prometheus metrics exposed at port 3004
      - "3004:3000"
    command: ["sqd", "process:prod:avax"]
    profiles:
      - avax

  eth-processor:
    <<: *defaults
    ports:
      # prometheus metrics exposed at port 3000
      - "3000:3000"
    command: ["sqd", "process:prod:eth"]
    profiles:
      - eth

  polygon-processor:
    <<: *defaults
    ports:
      # prometheus metrics exposed at port 3001
      - "3001:3000"
    command: ["sqd", "process:prod:polygon"]
    profiles:
      - polygon

  bsc-processor:
    <<: *defaults
    ports:
      # prometheus metrics exposed at port 3002
      - "3002:3000"
    command: ["sqd", "process:prod:bsc"]
    profiles:
      - bsc
