services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      # Uncomment for logging all SQL statements
      # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
    restart: always
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
    ports:
      # GraphQL endpoint at port 4350
      - "4350:4350"
    command: ["sqd", "serve:prod"]
    env_file:
      - .env
    depends_on:
      - db

  arbitrum-processor:
    build:
      context: .
    restart: always
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
    ports:
      # prometheus metrics exposed at port 3003
      - "3003:3000"
    command: ["sqd", "process:prod:arbitrum"]
    depends_on:
      - db
    env_file:
      - .env
    profiles:
      - arbitrum

  eth-processor:
    build:
      context: .
    restart: always
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
    ports:
      # prometheus metrics exposed at port 3000
      - "3000:3000"
    command: ["sqd", "process:prod:eth"]
    depends_on:
      - db
    env_file:
      - .env
    profiles:
      - eth

  polygon-processor:
    build:
      context: .
    restart: always
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
    ports:
      # prometheus metrics exposed at port 3001
      - "3001:3000"
    command: ["sqd", "process:prod:polygon"]
    depends_on:
      - db
    env_file:
      - .env
    profiles:
      - polygon

  bsc-processor:
    build:
      context: .
    restart: always
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
    ports:
      # prometheus metrics exposed at port 3002
      - "3002:3000"
    command: ["sqd", "process:prod:bsc"]
    depends_on:
      - db
    env_file:
      - .env
    profiles:
      - bsc
